# Generated by Django 4.0.4 on 2022-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('pcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_code',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=4)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('is_complete', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'todo_board',
            },
        ),
    ]
